#!/bin/bash
set -e;

monitors=($(xrandr --listmonitors | tail -n +2 | rev | cut -d' ' -f 1 | rev));
brightness_percentage="$(cat ~/.config/user/brightness)";

if   [[ "$1" =~ ^(\+|\-)[0-9]+$ ]]; then
  final_brightness_percentage="$(echo "$(("$brightness_percentage" + "$1"))")";
elif [[ "$1" =~ ^s(\+|\-)?[0-9]+$ ]]; then
  final_brightness_percentage="${1:1}";
else
  >&2 echo "Invalid brightness";
  exit 1;
fi

final_brightness_decimal="$(echo "$final_brightness_percentage" | awk '{ print $1/100 }')";

for monitor in "${monitors[@]}"; do
  xrandr --output "$monitor" --brightness "$final_brightness_decimal"
  echo "Monitor: '$monitor'";
  echo "Brightness: '$final_brightness_decimal'";
done

echo "$final_brightness_percentage" > ~/.config/user/brightness;
